#%RAML 0.8
---
title: Esendex
baseUri: https://api.esendex.com
version: 2016-01-27
securitySchemes:
  - basic:
      description: Esendex requires Basic Authentication for every API request
      type: Basic Authentication
securedBy: [basic]
traits:
  - paged:
      description: This resource is paged
      queryParameters:
        startindex:
          description: The zero-based index of the first resource to return
          type: number
          default: 0
        count:
          description: The number of resources to return
          type: number
          default: 100
  - accountFiltered:
      description: This resource can be filtered by a specific account reference
      queryParameters:
        filterBy:
          description: A filter name which must be followed by a filterValue parameter
          type: string
          example: account
        filterValue:
          description: A filter value which must follow a filterBy parameter
          type: string
          example: EX000000
  - accountReferenceFiltered:
      description: This resource must be filtered with an account reference
      queryParameters:
        accountReference:
          description: A valid account reference
          type: string
          example: EX000000
/v1.0:
  /messagedispatcher:
    displayName: Message Dispatcher
    description: |
      The Message Dispatcher resource can be used to send one or more SMS and Voice
      messages either straight away or scheduled in the future at a later point. The XML
      request object will contain the details of the message(s) to be sent and will
      generate a message batch response containing a URI to allow future queries to
      discover the status of the message(s).
    post:
      body:
        application/xml:
          schema: !include schemas/v1.0/requests/messagedispatcher/post.xsd
          example: !include examples/v1.0/requests/messagedispatcher/post.xml
      responses:
        200:
          body:
            application/xml:
              schema: !include schemas/v1.0/responses/messagedispatcher/post.xsd
              example: !include examples/v1.0/responses/messagedispatcher/post.xml
  /accounts:
    displayName: Accounts
    get:
      responses:
        200:
          body:
            application/xml:
              example: !include examples/v1.0/responses/accounts/get-all.xml
    /{accountId}:
      uriParameters:
        accountId:
          displayName: Account ID
          type: string
          pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$ # a GUID
          minLength: 36
          maxLength: 36
      get:
        responses:
          200:
            body:
              application/xml:
                example: !include examples/v1.0/responses/accounts/get-single.xml
      put:
        body:
          application/xml:
            schema: !include schemas/v1.0/requests/accounts/put.xsd
            example: !include examples/v1.0/requests/accounts/put.xml
        responses:
          200:
      /settings:
        get:
          responses:
            200:
              body:
                application/xml:
                  example: !include examples/v1.0/responses/accounts/settings/get.xml
        put:
          body:
            application/xml:
              schema: !include schemas/v1.0/requests/accounts/settings/put.xsd
              example: !include examples/v1.0/requests/accounts/settings/put.xml
          responses:
            200:
              body:
                application/xml:
                  example: !include examples/v1.0/responses/accounts/settings/get.xml
  /messageheaders:
    displayName: Message Headers
    description: |
      The Message Headers resource can be used to query messages which have been sent
      from an Esendex Account. It also allows individual Messages to be queried for more
      details.
    get:
      is: [paged]
      responses:
        200:
          body:
            application/xml:
              # schema: !include schemas/v1.0/responses/messageheaders/get-all.xsd
              example: !include examples/v1.0/responses/messageheaders/get-all.xml
    /{messageHeaderId}:
      uriParameters:
        messageHeaderId:
          displayName: Message Header ID
          type: string
          pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$ # a GUID
          minLength: 36
          maxLength: 36
      get:
        responses:
          200:
            body:
              application/xml:
                # schema: !include schemas/v1.0/responses/messageheaders/get-single.xsd
                example: !include examples/v1.0/responses/messageheaders/get-single.xml
  /inbox:
    /messages:
      displayName: Inbox Messages
      description: |
        The Inbox resource can be used to query Messages which have been received into
        an Esendex Account. The most common uses of the Inbox resource are to 'pull'
        (retrieve) the Inbound Messages and delete those Messages that have been processed.
      get:
        is: [paged]
        queryParameters:
          start:
            displayName: The start date to filter the results from, represented in ISO 8601 format.
            type: string
            pattern: ^\d{4}-\d{2}-\d{2}T\d{2}\:\d{2}\:\d{2}(?:[+-]\d{2}\:\d{2})|Z$
            minLength: 20
            maxLength: 25
          finish:
            displayName: The end date to filter the results to, represented in ISO 8601 format.
            type: string
            pattern: ^\d{4}-\d{2}-\d{2}T\d{2}\:\d{2}\:\d{2}(?:[+-]\d{2}\:\d{2})|Z$
            minLength: 20
            maxLength: 25
            example: '2016-01-04T13:18:20Z'
        responses:
          200:
            body:
              application/xml:
                example: !include examples/v1.0/responses/inbox/messages/get-all.xml
  /messagesinformation:
    displayName: Messages Information
    description: |
      The Messages Information resource can be used to obtain information for a message
      to help understand the costs involved in sending the message.
    post:
      displayName: Analyse one or more messages
      description: |
        Analyse one or more messages for information such as the character set it falls
        into, and the number of parts required to send the message.
      body:
        application/xml:
          schema: !include schemas/v1.0/requests/messages/information/post.xsd
          example: !include examples/v1.0/requests/messages/information/post.xml
      responses:
        200:
          body:
            application/xml:
              schema: !include schemas/v1.0/responses/messages/information/post.xsd
              example: !include examples/v1.0/responses/messages/information/post.xml
/v1.1:
  /messagebatches:
    displayName: Message Headers
    description: |
      The Message Batches resource can be used to query the Batches of Messages which
      have been sent from an Esendex Account. A common use of the Message Batches
      resource is to retrieve a summary of the status codes for the Messages which
      indicates the delivery progress. Any Message Batches scheduled to be sent in
      sthe future can also be cancelled.
    get:
      displayName: Retrieve Message Batches
      description: Retrieves a list of Message Batches
      is: [paged, accountFiltered]
      responses:
        200:
          body:
            application/xml:
              example: !include examples/v1.1/responses/messagebatches/get-all.xml
    /{messageBatchId}:
      uriParameters:
        messageBatchId:
          displayName: Message Batch ID
          type: string
          pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$ # a GUID
          minLength: 36
          maxLength: 36
      get:
        displayName: Retrieve a single Message Batch
        description: Retrieves a single Message Batch identified by ID
        responses:
          200:
            headers:
              ETag:
                description: The concurrency ID of the Message Batch for use when setting the batch name
                example: |
                  ETag: "e461a6a7-be6e-4e73-9221-0c9bdfe5d6d9"
            body:
              application/xml:
                example: !include examples/v1.1/responses/messagebatches/get-single.xml
      put:
        displayName: Name a Message Batch
        description: |
          Sets a name for the Message Batch which will be available when subsequently
          retrieving the Message Batch resource
        headers:
          If-Match:
            type: string
            required: false
            description: |
              When set, will fail any request where the Message Batch concurrency ID is
              different to the one specified
            example: |
              If-Match: "e461a6a7-be6e-4e73-9221-0c9bdfe5d6d9"
          If-None-Match:
            type: string
            required: false
            description: |
              When set, will fail any request where the Message Batch concurrency ID is
              the same as the one specified
            example: |
              If-None-Match: "e461a6a7-be6e-4e73-9221-0c9bdfe5d6d9"
        responses:
          204:
            headers:
              ETag:
                description: The concurrency ID of the Message Batch
          412:
      /schedule:
        delete:
          displayName: Delete a scheduled Message Batch.
          description: |
            If a Message Batch is scheduled to go out at a later time and this time is
            outside the cut off period of 5 minutes, the Message Batch response will
            contain a LINK element with REL attribute with value CANCEL. The HREF
            attribute for the LINK element provides a URI for cancelling the sending of
            a scheduled Batch.
          responses:
            204:
/v2.0:
  /contacts:
    displayName: Contacts
    description: |
      The Contacts resource allows the retrieval and creation of named contacts and
      telephone numbers. Contacts are associated with an account and must be unique by
      both quick name and phone number within the account, and must not be the same as
      any contact group name within the same account.
    get:
      displayName: Retrieve All Contacts
      description: Retrieves a paged response of contacts within the specified account.
      is: [paged, accountReferenceFiltered]
      responses:
        200:
          body:
            application/xml:
              schema: !include schemas/v2.0/responses/contacts/get-all.xsd
              example: !include examples/v2.0/responses/contacts/get-all.xml
    post:
      displayName: Create a Contact
      description: Creates a new contact and returns the created contact in the response.
      body:
        application/xml:
          schema: !include schemas/v2.0/requests/contacts/post.xsd
          example: !include examples/v2.0/requests/contacts/post.xml
      responses:
        200:
          body:
            application/xml:
              schema: !include schemas/v2.0/responses/contacts/post.xsd
              example: !include examples/v2.0/responses/contacts/post.xml
    /{contactId}:
      uriParameters:
        contactId:
          displayName: Contact ID
          type: string
          pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$ # a GUID
          minLength: 36
          maxLength: 36
      get:
        displayName: Retrieve a Single Contact
        description: Retrieves a contact identified by ID.
        responses:
          200:
            body:
              application/xml:
                example: !include examples/v2.0/responses/contacts/get-single.xml
      put:
        displayName: Update a Contact
        description: Amends an existing contact.
        body:
          application/xml:
            schema: !include schemas/v2.0/requests/contacts/put.xsd
            example: !include examples/v2.0/requests/contacts/put.xml
        responses:
          200:
            body:
              application/xml:
                schema: !include schemas/v2.0/responses/contacts/put.xsd
                example: !include examples/v2.0/responses/contacts/put.xml
      delete:
        displayName: Delete a Contact
        description: Deletes an existing contact. _This operation cannot be undone!_
        responses:
          204:
  /contactgroups:
    displayName: Contact Groups
    description: |
      The contact groups resource allows the retrieval and creation of named groups which
      can be used to collect together one or more contacts. The name of a contact group
      must be unique per account, and must not be the same as any contact quick names
      within the same account.
    get:
      displayName: Retrieve All Contact Groups
      description: Retrieves a paged response of contact groups within the specified account.
      is: [paged, accountReferenceFiltered]
      responses:
        200:
          body:
            application/xml:
              example: !include examples/v2.0/responses/contactgroups/get-all.xml
    post:
      displayName: Create a Contact Group
      description: Creates a new contact group and returns the created contact group in the response.
      body:
        application/xml:
          schema: !include schemas/v2.0/requests/contactgroups/post.xsd
          example: !include examples/v2.0/requests/contactgroups/post.xml
      responses:
        200:
          body:
            application/xml:
              schema: !include schemas/v2.0/responses/contactgroups/post.xsd
              example: !include examples/v2.0/responses/contactgroups/post.xml
    /{contactGroupId}:
      uriParameters:
        contactGroupId:
          displayName: Contact Group ID
          type: string
          pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$ # a GUID
          minLength: 36
          maxLength: 36
      get:
        displayName: Retrieve a Single Contact Group
        description: Retrieves a contact group identified by ID.
        responses:
          200:
            body:
              application/xml:
                example: !include examples/v2.0/responses/contactgroups/get-single.xml
      put:
        displayName: Update a Contact Group
        description: Amends an existing contact group.
        body:
          application/xml:
            schema: !include schemas/v2.0/requests/contactgroups/put.xsd
            example: !include examples/v2.0/requests/contactgroups/put.xml
        responses:
          200:
            body:
              application/xml:
                schema: !include schemas/v2.0/responses/contactgroups/put.xsd
                example: !include examples/v2.0/responses/contactgroups/put.xml
      delete:
        displayName: Delete a Contact Group
        description: Deletes an existing contact group. _This operation cannot be undone!_
        responses:
          204:
      /contacts:
        get:
          displayName: Retrieve Contacts in a Contact Group
          description: |
            Retrieves a paged response of contacts within the specified contact group.
            See the contacts documentation for details of the elements returned when
            getting contacts in a contact group.
          responses:
            200:
              body:
                application/xml:
                  example: !include examples/v2.0/responses/contactgroups/contacts/get-all.xml
        post:
          displayName: Add a Contact to a Contact Group
          description: Adds a contact to the specified contact group.
          body:
            application/xml:
              example: !include examples/v2.0/requests/contactgroups/contacts/post.xml
          responses:
            204:
        /{contactId}:
          uriParameters:
            contactId:
              displayName: Contact ID
              type: string
              pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$ # a GUID
              minLength: 36
              maxLength: 36
          delete:
            displayName: Remove a Contact from a Contact Group
            description: Removes a contact from the specified contact group.
            responses:
              204: